"""empty message

Revision ID: 9e93c5169782
Revises: 99d25fa87893
Create Date: 2022-03-27 02:49:11.817081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e93c5169782'
down_revision = '99d25fa87893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('print_queue', sa.Column('account', sa.String(length=120), nullable=False, server_default='Unknown'))
    # ### end Alembic commands ###

