"""empty message

Revision ID: fbb566c27690
Revises: 
Create Date: 2022-03-25 17:12:04.661680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb566c27690'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('file_location', sa.String(length=520), nullable=False),
    sa.Column('total_copies', sa.Integer(), nullable=False),
    sa.Column('pages', sa.String(length=120), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('print_progress_status', sa.String(length=120), nullable=False),
    sa.Column('payment_method', sa.String(length=120), nullable=False),
    sa.Column('payment_transaction_id', sa.String(length=120), nullable=False),
    sa.Column('payment_verification_status', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_location'),
    sa.UniqueConstraint('payment_transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_queue')
    # ### end Alembic commands ###
